### ISSUE TITLE
Linux Ubuntu 20.04 LTS: Software does not output Report 

### ISSUE THREAD

**Issue by fi7855ar** [snijderlab/stitch#171]
Hi,
I was trying to run stitch on a Linux Ubuntu 20.04 LTS. It runs but doesn't give any output for either HTML or CSV.
Batchfiles with corresponding command:

[basic_csv.txt](https://github.com/snijderlab/stitch/files/8907572/basic_csv.txt)

`
$ stitch/bin/release/net6.0/linux-x64/stitch batchfiles/basic_csv.txt >> basic_csv.log 2> basic_csv.err
`

[basic.txt](https://github.com/snijderlab/stitch/files/8907573/basic.txt)

`
$ stitch/bin/release/net6.0/linux-x64/stitch` batchfiles/basic.txt >> basic.log 2> basic.err

Logfiles (both .err were empty) :
[basic_csv.log](https://github.com/snijderlab/stitch/files/8907632/basic_csv.log)
[basic.log](https://github.com/snijderlab/stitch/files/8907633/basic.log)

The only output I get are empty directories from the basic.txt (HTML report) run

tree results/
results/
└── 2022-06-15@10-30-37 Basic run
    └── report-basic

2 directories, 0 files

--------------------------------------------------------
Best,
Filip

**Comment by douweschulte** [comment]
Thanks a lot for opening the issue! Apparently I wrote code in the saving functionality that was purely windows focussed. The commit that was just added should fix this issue. A single tests gives me headaches since yesterday, but you can find the new executables with this fix in place here: https://github.com/snijderlab/stitch/actions/runs/2501307897. Thanks to this issue I also figured out that the Linux executables where packaged erroneously. But in any case it is if course possible to build the binary yourself.
If you find any more issues feel free to report them back. And thanks for the in depth error report.

**Comment by fi7855ar** [comment]
No, thank you for the blazing fast fix and reply! I'll have a go at it again with the nightly build as you linked to, else I can try building it from scratch. I keep my fingers crossed!
