### ISSUE TITLE
Getting Started Script for Windows Unsuccessful

### ISSUE THREAD

**Issue by kostrouc** [snijderlab/stitch#202]
Hi,

I followed the instructions on downloading dotnet runtime for x64 on Windows and downloading the stitch Windows zip folder. I unzipped the stitch folder and ran the ".\stitch.exe batchfiles\monoclonal.txt" script in Command Prompt and it could not find a "RawDataDirectory" to complete the test run. Please advise on how to correctly run the test script. 

Below is the following command prompt script that was run:

```
Directory of C:\Users\kostrouchov\Downloads

11/04/2022  10:45 AM    <DIR>          .
11/04/2022  10:45 AM    <DIR>          ..
10/21/2022  10:29 AM    <DIR>          alphabets
10/21/2022  10:29 AM    <DIR>          assets
10/21/2022  10:29 AM    <DIR>          batchfiles
10/21/2022  10:29 AM    <DIR>          datasets
11/04/2022  10:24 AM        27,912,752 dotnet-runtime-6.0.10-win-x64.exe
10/21/2022  10:29 AM    <DIR>          images
10/21/2022  10:29 AM             1,105 License.md
10/21/2022  10:29 AM             4,308 README.md
11/04/2022  10:14 AM        98,339,213 stitch-v1.3.0-windows.zip
10/21/2022  10:29 AM        91,327,396 stitch.exe
10/21/2022  10:29 AM        91,927,336 stitch_arm.exe
10/21/2022  10:29 AM    <DIR>          templates
               6 File(s)    309,512,110 bytes
               8 Dir(s)  132,489,383,936 bytes free

C:\Users\kostrouchov\Downloads>.\stitch.exe batchfiles\monoclonal.txt
Could not find RawDataDirectory.                                                      |   0%  43 ms
  ╭── C:\Users\kostrouchov\Downloads\batchfiles\batchfiles\monoclonal.txt:4:20
  │
2 │ Version         : 1.3
>                                                                                     |   0%  1.1 3 │ Runname         : Monoclonal Herceptin
4 │ RawDataDirectory: R:\F1\peng0013\201912
  ·                   ─────────────────────
5 │
6 │ - Here the input can be defined, this will be used in the TemplateMatching and Recombine steps
  ╵
note: Execution will continue, but the spectra will be missing from all reports.

------------------------------------------------------------------------------------->| 100% 15.3 s
```

**Comment by douweschulte** [comment]
This warning that is shown to you means that the raw data could not be found, which is what I expected to see because it is not bundled with the program because it takes up so much space. As you see in the warning message the program just continues but there will be no spectra shown in the HTML report. If you take a look in `.\results\` you will find the generated html report there.

I do agree that this is a bit daunting as the first thing you see when you run it so I will remove the raw data line from the example. Thanks for reaching out.

If you have any further questions feel free to ask away.

**Comment by kostrouc** [comment]
Thank you!
