### ISSUE TITLE
error in basic search

### ISSUE THREAD

**Issue by pikiton** [snijderlab/stitch#241]
![Screenshot 2023-11-08 014042](https://github.com/snijderlab/stitch/assets/120220014/eec74b65-3c48-4178-be3f-dd0c6fad5e38)

**Comment by pikiton** [comment]
search in monoclonal work good with this file from X+. Files in attachment
[AAV_denovo_X_50.csv](https://github.com/snijderlab/stitch/files/13289826/AAV_denovo_X_50.csv)
[basicAAV.txt](https://github.com/snijderlab/stitch/files/13289828/basicAAV.txt)

**Comment by douweschulte** [comment]
Thanks for raising the issue! I am sorry for the crash, the issue is that the file you specified in the `segment` (`../datasets/report-monoclonal.fasta`) does not exist. After this error the code is left in a broken state and tries to detect other ways in which parsing can go wrong which leads it to this crash. 
If this does not fix your problem please let me know. I will take a look if this error is still in my development version and fix it there if applicable.

**Comment by douweschulte** [comment]
I just checked and the development version has this issue already patched. If you want you could move to this version, which also contains some other improvements. (Please note that the command line interface has changed, you now have to type `stitch run <file>` instead of `stitch <file>`).

The nightly version can be found [on the github actions tab](https://github.com/snijderlab/stitch/actions?query=branch%3Amaster) and then pick the latest one, scroll down and get the version for your architecture.
