### ISSUE TITLE
Index out of range 

### ISSUE THREAD

**Issue by MengTingHe2023** [snijderlab/stitch#243]
I encountered the following error while using Stitch.

**Comment by MengTingHe2023** [comment]
![eddc6cc82b78cb2003eed5a722b841a](https://github.com/snijderlab/stitch/assets/145458868/0c80a5fd-94b6-4672-9140-47f68ad450ab)

**Comment by douweschulte** [comment]
After looking at the specified function I think I found one potential route for this crash. But to be actually sure I would have to debug it on my side. So you can either wait for the next nightly release (in about 1 hour) and try to see if it works, or send me the data you used to run so that I can debug it on my side and see what the actual reason for the crash is.

**Comment by MengTingHe2023** [comment]
Thank you very much! The nightly version you provided runs successfully.
